name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  url_launcher: ^6.3.2
  # --- AQUÍ AGREGAMOS LAS NUEVAS LIBRERÍAS ---
  pdf: ^3.10.0
  printing: ^5.11.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # Nota: No agregues nada debajo de 'flutter:' a menos que sean assets o fonts.